const carDatabase: Record<string, string[]> = {
    Abarth: ['500', '595', '695', '124 Spider'],
    AlfaRomeo: ['Giulietta', 'Giulia', 'Stelvio', 'Tonale', 'MiTo', '4C'],
    Aston_Martin: ['Vantage', 'DB11', 'DB12', 'DBS', 'DBX', 'Rapide', 'Vanquish'],
    Audi: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron', 'e-tron GT', 'RS3', 'RS4', 'RS6', 'S3', 'S4'],
    Bentley: ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
    BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'i5', 'i7', 'iX', 'iX1', 'iX3', 'M2', 'M3', 'M4', 'M5'],
    Citroen: ['C1', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C5 Aircross', 'Berlingo', 'DS3', 'DS4', 'DS5', 'e-C4', 'Ami'],
    Cupra: ['Leon', 'Formentor', 'Born', 'Ateca', 'Tavascan'],
    Dacia: ['Sandero', 'Duster', 'Jogger', 'Spring', 'Logan'],
    DS: ['DS 3', 'DS 4', 'DS 7', 'DS 9'],
    Ferrari: ['Roma', 'Portofino', 'F8 Tributo', '296 GTB', 'SF90', '812 Superfast', 'Purosangue'],
    Fiat: ['500', '500X', '500L', '500e', 'Panda', 'Tipo', 'Punto', 'Doblo'],
    Ford: ['Ka', 'Fiesta', 'Focus', 'Puma', 'Kuga', 'EcoSport', 'Mondeo', 'Mustang', 'Mustang Mach-E', 'Edge', 'Galaxy', 'S-Max', 'Transit', 'Transit Custom', 'Ranger', 'Explorer'],
    Genesis: ['G70', 'G80', 'GV60', 'GV70', 'GV80'],
    Honda: ['Jazz', 'Civic', 'CR-V', 'HR-V', 'e', 'ZR-V', 'Accord'],
    Hyundai: ['i10', 'i20', 'i30', 'i40', 'Bayon', 'Kona', 'Tucson', 'Santa Fe', 'Ioniq', 'Ioniq 5', 'Ioniq 6', 'Nexo'],
    Jaguar: ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace'],
    Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Avenger'],
    Kia: ['Picanto', 'Rio', 'Ceed', 'ProCeed', 'XCeed', 'Stonic', 'Soul', 'Sportage', 'Sorento', 'Niro', 'EV6', 'EV9', 'Stinger'],
    Land_Rover: ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Freelander'],
    Lexus: ['CT', 'IS', 'ES', 'LS', 'UX', 'NX', 'RX', 'RZ', 'LC', 'RC'],
    Lotus: ['Elise', 'Exige', 'Evora', 'Emira', 'Eletre'],
    Maserati: ['Ghibli', 'Quattroporte', 'Levante', 'Grecale', 'MC20', 'GranTurismo'],
    Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'MX-5', 'MX-30'],
    McLaren: ['570S', '720S', '765LT', 'Artura', 'GT'],
    Mercedes: ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'SL', 'AMG GT', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'V-Class'],
    MG: ['MG3', 'MG4', 'MG5', 'ZS', 'HS', 'MG Cyberster'],
    Mini: ['Hatch', '3-Door', '5-Door', 'Clubman', 'Countryman', 'Convertible', 'Electric', 'Paceman', 'Coupe'],
    Mitsubishi: ['Mirage', 'ASX', 'Eclipse Cross', 'Outlander', 'Shogun', 'L200'],
    Nissan: ['Micra', 'Note', 'Juke', 'Qashqai', 'X-Trail', 'Leaf', 'Ariya', 'Navara', 'GT-R', '370Z'],
    Peugeot: ['108', '208', '308', '408', '508', '2008', '3008', '5008', 'e-208', 'e-2008', 'Partner', 'Rifter'],
    Polestar: ['Polestar 2', 'Polestar 3', 'Polestar 4'],
    Porsche: ['911', '718 Cayman', '718 Boxster', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
    Renault: ['Clio', 'Captur', 'Megane', 'Megane E-Tech', 'Kadjar', 'Arkana', 'Austral', 'Zoe', 'Scenic', 'Twingo', 'Kangoo'],
    Rolls_Royce: ['Ghost', 'Phantom', 'Wraith', 'Dawn', 'Cullinan', 'Spectre'],
    Seat: ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Mii'],
    Skoda: ['Citigo', 'Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Rapid'],
    Smart: ['ForTwo', 'ForFour', '#1', '#3'],
    SsangYong: ['Tivoli', 'Korando', 'Rexton', 'Musso'],
    Subaru: ['Impreza', 'XV', 'Forester', 'Outback', 'Levorg', 'BRZ'],
    Suzuki: ['Ignis', 'Swift', 'Baleno', 'Vitara', 'S-Cross', 'Jimny', 'Across', 'Swace'],
    Tesla: ['Model 3', 'Model Y', 'Model S', 'Model X'],
    Toyota: ['Aygo', 'Aygo X', 'Yaris', 'Yaris Cross', 'Corolla', 'C-HR', 'RAV4', 'Prius', 'Camry', 'Highlander', 'bZ4X', 'GR86', 'GR Yaris', 'Supra', 'Hilux', 'Proace'],
    Vauxhall: ['Corsa', 'Astra', 'Mokka', 'Crossland', 'Grandland', 'Insignia', 'Combo', 'Vivaro', 'Adam', 'Viva', 'Corsa-e', 'Mokka-e'],
    Volkswagen: ['up!', 'Polo', 'Golf', 'Passat', 'Arteon', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'Touran', 'Sharan', 'ID.3', 'ID.4', 'ID.5', 'ID.7', 'ID.Buzz', 'Caddy', 'Transporter'],
    Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40', 'EX30', 'EX90'],
  };
  
  export default carDatabase;
  