/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    vehicles: Vehicle;
    makes: Make;
    enquiries: Enquiry;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    makes: MakesSelect<false> | MakesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'company-settings': CompanySetting;
  };
  globalsSelect: {
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image, e.g. "Front view of blue BMW 320d".
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  /**
   * e.g. "2019 BMW 320d M Sport"
   */
  title: string;
  /**
   * Auto-filled from the title. Leave blank.
   */
  slug?: string | null;
  make:
    | 'Abarth'
    | 'AlfaRomeo'
    | 'Aston Martin'
    | 'Audi'
    | 'Bentley'
    | 'BMW'
    | 'Citroen'
    | 'Cupra'
    | 'Dacia'
    | 'DS'
    | 'Ferrari'
    | 'Fiat'
    | 'Ford'
    | 'Genesis'
    | 'Honda'
    | 'Hyundai'
    | 'Jaguar'
    | 'Jeep'
    | 'Kia'
    | 'Land Rover'
    | 'Lexus'
    | 'Lotus'
    | 'Maserati'
    | 'Mazda'
    | 'McLaren'
    | 'Mercedes'
    | 'MG'
    | 'Mini'
    | 'Mitsubishi'
    | 'Nissan'
    | 'Peugeot'
    | 'Polestar'
    | 'Porsche'
    | 'Renault'
    | 'Rolls Royce'
    | 'Seat'
    | 'Skoda'
    | 'Smart'
    | 'SsangYong'
    | 'Subaru'
    | 'Suzuki'
    | 'Tesla'
    | 'Toyota'
    | 'Vauxhall'
    | 'Volkswagen'
    | 'Volvo';
  model:
    | '#1'
    | '#3'
    | '1 Series'
    | '108'
    | '124 Spider'
    | '2 Series'
    | '2008'
    | '208'
    | '296 GTB'
    | '3 Series'
    | '3-Door'
    | '3008'
    | '308'
    | '370Z'
    | '4 Series'
    | '408'
    | '4C'
    | '5 Series'
    | '5-Door'
    | '500'
    | '5008'
    | '500L'
    | '500X'
    | '500e'
    | '508'
    | '570S'
    | '595'
    | '6 Series'
    | '695'
    | '7 Series'
    | '718 Boxster'
    | '718 Cayman'
    | '720S'
    | '765LT'
    | '8 Series'
    | '812 Superfast'
    | '911'
    | 'A-Class'
    | 'A1'
    | 'A2'
    | 'A3'
    | 'A4'
    | 'A5'
    | 'A6'
    | 'A7'
    | 'A8'
    | 'AMG GT'
    | 'ASX'
    | 'Accord'
    | 'Across'
    | 'Adam'
    | 'Ami'
    | 'Ariya'
    | 'Arkana'
    | 'Arona'
    | 'Arteon'
    | 'Artura'
    | 'Astra'
    | 'Ateca'
    | 'Austral'
    | 'Avenger'
    | 'Aygo'
    | 'Aygo X'
    | 'B-Class'
    | 'BRZ'
    | 'Baleno'
    | 'Bayon'
    | 'Bentayga'
    | 'Berlingo'
    | 'Born'
    | 'C-Class'
    | 'C-HR'
    | 'C1'
    | 'C3'
    | 'C3 Aircross'
    | 'C4'
    | 'C4 Cactus'
    | 'C40'
    | 'C5 Aircross'
    | 'CLA'
    | 'CLS'
    | 'CR-V'
    | 'CT'
    | 'CX-3'
    | 'CX-30'
    | 'CX-5'
    | 'CX-60'
    | 'Caddy'
    | 'Camry'
    | 'Captur'
    | 'Cayenne'
    | 'Ceed'
    | 'Cherokee'
    | 'Citigo'
    | 'Civic'
    | 'Clio'
    | 'Clubman'
    | 'Combo'
    | 'Compass'
    | 'Continental GT'
    | 'Convertible'
    | 'Corolla'
    | 'Corsa'
    | 'Corsa-e'
    | 'Countryman'
    | 'Coupe'
    | 'Crossland'
    | 'Cullinan'
    | 'DB11'
    | 'DB12'
    | 'DBS'
    | 'DBX'
    | 'DS 3'
    | 'DS 4'
    | 'DS 7'
    | 'DS 9'
    | 'DS3'
    | 'DS4'
    | 'DS5'
    | 'Dawn'
    | 'Defender'
    | 'Discovery'
    | 'Discovery Sport'
    | 'Doblo'
    | 'Duster'
    | 'E-Class'
    | 'E-Pace'
    | 'EQA'
    | 'EQB'
    | 'EQC'
    | 'EQE'
    | 'EQS'
    | 'ES'
    | 'EV6'
    | 'EV9'
    | 'EX30'
    | 'EX90'
    | 'Eclipse Cross'
    | 'EcoSport'
    | 'Edge'
    | 'Electric'
    | 'Eletre'
    | 'Elise'
    | 'Emira'
    | 'Enyaq'
    | 'Evora'
    | 'Exige'
    | 'Explorer'
    | 'F-Pace'
    | 'F-Type'
    | 'F8 Tributo'
    | 'Fabia'
    | 'Fiesta'
    | 'Flying Spur'
    | 'Focus'
    | 'ForFour'
    | 'ForTwo'
    | 'Forester'
    | 'Formentor'
    | 'Freelander'
    | 'G-Class'
    | 'G70'
    | 'G80'
    | 'GLA'
    | 'GLB'
    | 'GLC'
    | 'GLE'
    | 'GLS'
    | 'GR Yaris'
    | 'GR86'
    | 'GT'
    | 'GT-R'
    | 'GV60'
    | 'GV70'
    | 'GV80'
    | 'Galaxy'
    | 'Ghibli'
    | 'Ghost'
    | 'Giulia'
    | 'Giulietta'
    | 'Golf'
    | 'GranTurismo'
    | 'Grand Cherokee'
    | 'Grandland'
    | 'Grecale'
    | 'HR-V'
    | 'HS'
    | 'Hatch'
    | 'Highlander'
    | 'Hilux'
    | 'I-Pace'
    | 'ID.3'
    | 'ID.4'
    | 'ID.5'
    | 'ID.7'
    | 'ID.Buzz'
    | 'IS'
    | 'Ibiza'
    | 'Ignis'
    | 'Impreza'
    | 'Insignia'
    | 'Ioniq'
    | 'Ioniq 5'
    | 'Ioniq 6'
    | 'Jazz'
    | 'Jimny'
    | 'Jogger'
    | 'Juke'
    | 'Ka'
    | 'Kadjar'
    | 'Kamiq'
    | 'Kangoo'
    | 'Karoq'
    | 'Kodiaq'
    | 'Kona'
    | 'Korando'
    | 'Kuga'
    | 'L200'
    | 'LC'
    | 'LS'
    | 'Leaf'
    | 'Leon'
    | 'Levante'
    | 'Levorg'
    | 'Logan'
    | 'M2'
    | 'M3'
    | 'M4'
    | 'M5'
    | 'MC20'
    | 'MG Cyberster'
    | 'MG3'
    | 'MG4'
    | 'MG5'
    | 'MX-30'
    | 'MX-5'
    | 'Macan'
    | 'Mazda2'
    | 'Mazda3'
    | 'Mazda6'
    | 'Megane'
    | 'Megane E-Tech'
    | 'MiTo'
    | 'Micra'
    | 'Mii'
    | 'Mirage'
    | 'Model 3'
    | 'Model S'
    | 'Model X'
    | 'Model Y'
    | 'Mokka'
    | 'Mokka-e'
    | 'Mondeo'
    | 'Mulsanne'
    | 'Musso'
    | 'Mustang'
    | 'Mustang Mach-E'
    | 'NX'
    | 'Navara'
    | 'Nexo'
    | 'Niro'
    | 'Note'
    | 'Octavia'
    | 'Outback'
    | 'Outlander'
    | 'Paceman'
    | 'Panamera'
    | 'Panda'
    | 'Partner'
    | 'Passat'
    | 'Phantom'
    | 'Picanto'
    | 'Polestar 2'
    | 'Polestar 3'
    | 'Polestar 4'
    | 'Polo'
    | 'Portofino'
    | 'Prius'
    | 'ProCeed'
    | 'Proace'
    | 'Puma'
    | 'Punto'
    | 'Purosangue'
    | 'Q2'
    | 'Q3'
    | 'Q4 e-tron'
    | 'Q5'
    | 'Q7'
    | 'Q8'
    | 'Qashqai'
    | 'Quattroporte'
    | 'R8'
    | 'RAV4'
    | 'RC'
    | 'RS3'
    | 'RS4'
    | 'RS6'
    | 'RX'
    | 'RZ'
    | 'Range Rover'
    | 'Range Rover Evoque'
    | 'Range Rover Sport'
    | 'Range Rover Velar'
    | 'Ranger'
    | 'Rapid'
    | 'Rapide'
    | 'Renegade'
    | 'Rexton'
    | 'Rifter'
    | 'Rio'
    | 'Roma'
    | 'S-Class'
    | 'S-Cross'
    | 'S-Max'
    | 'S3'
    | 'S4'
    | 'S60'
    | 'S90'
    | 'SF90'
    | 'SL'
    | 'Sandero'
    | 'Santa Fe'
    | 'Scala'
    | 'Scenic'
    | 'Sharan'
    | 'Shogun'
    | 'Sorento'
    | 'Soul'
    | 'Spectre'
    | 'Sportage'
    | 'Spring'
    | 'Stelvio'
    | 'Stinger'
    | 'Stonic'
    | 'Superb'
    | 'Supra'
    | 'Swace'
    | 'Swift'
    | 'T-Cross'
    | 'T-Roc'
    | 'TT'
    | 'Tarraco'
    | 'Tavascan'
    | 'Taycan'
    | 'Tiguan'
    | 'Tipo'
    | 'Tivoli'
    | 'Tonale'
    | 'Touareg'
    | 'Touran'
    | 'Transit'
    | 'Transit Custom'
    | 'Transporter'
    | 'Tucson'
    | 'Twingo'
    | 'UX'
    | 'V-Class'
    | 'V60'
    | 'V90'
    | 'Vanquish'
    | 'Vantage'
    | 'Vitara'
    | 'Viva'
    | 'Vivaro'
    | 'Wraith'
    | 'Wrangler'
    | 'X-Trail'
    | 'X1'
    | 'X2'
    | 'X3'
    | 'X4'
    | 'X5'
    | 'X6'
    | 'X7'
    | 'XC40'
    | 'XC60'
    | 'XC90'
    | 'XCeed'
    | 'XE'
    | 'XF'
    | 'XJ'
    | 'XV'
    | 'Yaris'
    | 'Yaris Cross'
    | 'Z4'
    | 'ZR-V'
    | 'ZS'
    | 'Zoe'
    | 'bZ4X'
    | 'e'
    | 'e-2008'
    | 'e-208'
    | 'e-C4'
    | 'e-tron'
    | 'e-tron GT'
    | 'i10'
    | 'i20'
    | 'i3'
    | 'i30'
    | 'i4'
    | 'i40'
    | 'i5'
    | 'i7'
    | 'iX'
    | 'iX1'
    | 'iX3'
    | 'up!';
  /**
   * M Sport, S line... (optional)
   */
  variant?: string | null;
  year: number;
  /**
   * In £
   */
  price: number;
  mileage: number;
  fuelType: 'Petrol' | 'Diesel' | 'Hybrid' | 'Electric' | 'PHEV' | 'Mild Hybrid';
  transmission: 'Manual' | 'Automatic';
  bodyType: 'Hatchback' | 'Saloon' | 'Estate' | 'SUV' | 'Coupe' | 'Convertible' | 'MPV' | 'Pickup' | 'Van';
  colour: string;
  /**
   * Number plate, e.g. AB19 CDE
   */
  registration?: string | null;
  /**
   * Litres (optional)
   */
  engineSize?: number | null;
  /**
   * (optional)
   */
  doors?: number | null;
  /**
   * (optional)
   */
  previousOwners?: number | null;
  /**
   * (optional)
   */
  serviceHistory?: ('Full' | 'Part' | 'None') | null;
  /**
   * e.g. "Heated seats", "Apple CarPlay"
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-text write-up shown on the detail page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * First image is the main/cover photo.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Available/Reserved → Stock page. Sold → Recently Sold page.
   */
  status: 'Available' | 'Reserved' | 'Sold';
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  /**
   * Warranty included.
   */
  warranty?: ('None' | '3 months' | '6 months' | '12 months') | null;
  /**
   * VAT qualifying vehicle.
   */
  vatQualifying?: boolean | null;
  /**
   * (optional)
   */
  soldPrice?: number | null;
  /**
   * Used to order Recently Sold.
   */
  soldDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes".
 */
export interface Make {
  id: number;
  /**
   * e.g. BMW, Audi, Ford
   */
  name: string;
  /**
   * All models for this make, e.g. 320d, A4, Focus
   */
  models?:
    | {
        model: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  /**
   * The car this enquiry is about (if any).
   */
  vehicle?: (number | null) | Vehicle;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'makes';
        value: number | Make;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  make?: T;
  model?: T;
  variant?: T;
  year?: T;
  price?: T;
  mileage?: T;
  fuelType?: T;
  transmission?: T;
  bodyType?: T;
  colour?: T;
  registration?: T;
  engineSize?: T;
  doors?: T;
  previousOwners?: T;
  serviceHistory?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  status?: T;
  featured?: T;
  warranty?: T;
  vatQualifying?: T;
  soldPrice?: T;
  soldDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes_select".
 */
export interface MakesSelect<T extends boolean = true> {
  name?: T;
  models?:
    | T
    | {
        model?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  vehicle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  companyName?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  openingHours?:
    | {
        /**
         * e.g. "Mon–Fri"
         */
        days?: string | null;
        /**
         * e.g. "9:00–18:00"
         */
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    /**
     * Number in international format, e.g. 447123456789
     */
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  companyName?: T;
  phone?: T;
  email?: T;
  address?: T;
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}